### ISSUE TITLE
DailyCodingProblem!

### ISSUE THREAD

**Issue by mrpalide** [amirkhaki/resume#1]
Hey AmirReza! What's up?

Check here: https://www.dailycodingproblem.com/

If you was interest call me back. I would like to discuss about problems with one or two others. I asked [Mahdi](https://github.com/mahdiZarepoor/AdventOfCodeSolution/issues/1), also will ask Mehdi too. ;)

Good luck!

**Comment by amirkhaki** [comment]
Hi, 

I'm interested and subscribed to mailing list.

**Comment by mrpalide** [comment]
Great!
I don't know about order of problems, but I get first of it today:

> This problem was recently asked by Google.
Given a list of numbers and a number k, return whether any two numbers from the list add up to k.
For example, given [10, 15, 3, 7] and k of 17, return true since 10 + 7 is 17.

Is it same as yours?

**Comment by amirkhaki** [comment]
Yes
